version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - embedg-local-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: embedg
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

  embedg:
    image: merlintor/embed-generator:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - EMBEDG_API__HOST=0.0.0.0
      - EMBEDG_POSTGRES__HOST=postgres
      - EMBEDG_POSTGRES__USER=postgres
      - EMBEDG_POSTGRES__DB=embedg
      - BOT_ACTIVITY_NAME=Message.Style # Set the default activity here
    volumes:
      - ./config.yaml:/root/config.yaml

volumes:
  embedg-local-postgres:
